services:
  app:
    image: mcr.microsoft.com/devcontainers/java:1-21-bookworm
    volumes:
      - ../:/workspaces/Muses_TFG:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    env_file:
      - ../.env

  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${DB_NAME:-${POSTGRES_DB:-muses}}
      POSTGRES_USER: ${DB_USER:-${POSTGRES_USER:-muses}}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-${POSTGRES_PASSWORD:-muses_super_safe_password}}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
